### ISSUE TITLE
"Undefined" Error

### ISSUE THREAD

**Issue by bjellesma** [slowe/apod#2]
When double clicking on areas not linked to image on the heatmap, the sky_clock and sky_position divs will give "undefined." Possibly make a switch case in the JavaScript so that if the text does come out to be undefined, it will show nothing.

**Comment by bjellesma** [comment]
This is noticed more when using google chrome because chrome will highlight the text on a double click. Besides that, the text blends into the dark background and is unseen

**Comment by slowe** [comment]
Sorry for the slow response. I've been cycling across Europe since the start of May and have just got back home. Are you looking at http://apod.it/map.html ? I'm just trying to work out if this issue should be for VirtualSky rather than apod. Thanks.

**Comment by bjellesma** [comment]
I just took a look at it and it seems to be running fine. Cycling across Europe is definitely a valid excuse lol

**Comment by slowe** [comment]
OK. I'll mark this as closed for now.
