### ISSUE TITLE
High quality image url

### ISSUE THREAD

**Issue by rafaelderolez** [slowe/apod#4]
Hey @slowe,

Is there any way we can retrieve the **hdurl** for a high quality image from the api?

Raf

**Comment by slowe** [comment]
@rafaelderolez I haven't been including the HD image in this JSON-LD file so far. However, the NASA API seems to give that https://api.nasa.gov/api.html#apod

**Comment by rafaelderolez** [comment]
@slowe I've converted my application to use the official NASA API instead of this large collection, thanks!
